name: Build and Deploy Containers
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish_Deploy:
      name: Publish and Deploy
      if: github.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v1 
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          token: ${{secrets.github_token}}     
          
      - name: Print new build number
        run: echo Build number is $BUILD_NUMBER   
      - uses: azure/docker-login@v1
        with:
          login-server: mtscontainers.azurecr.io
          username: ${{ secrets.DTS_AZURE_USERNAME }}
          password: ${{ secrets.DTS_AZURE_PASSWORD }}
      - uses: actions/checkout@v1
      
      - name: docker build and push client
        run: |
          docker build --build-arg DB_NAME=temp -t mtscontainers.azurecr.io/dts-emp-dir-client:latest ./_client/
          docker tag mtscontainers.azurecr.io/dts-emp-dir-client:latest mtscontainers.azurecr.io/dts-emp-dir-client:$BUILD_NUMBER
          docker push mtscontainers.azurecr.io/dts-emp-dir-client:latest
          docker push mtscontainers.azurecr.io/dts-emp-dir-client:$BUILD_NUMBER
          
      - name: docker build and push server
        run: |
          docker build --build-arg DB_NAME=temp -t mtscontainers.azurecr.io/dts-emp-dir-server:latest ./_server/
          docker tag mtscontainers.azurecr.io/dts-emp-dir-server:latest mtscontainers.azurecr.io/dts-emp-dir-server:$BUILD_NUMBER
          docker push mtscontainers.azurecr.io/dts-emp-dir-server:latest
          docker push mtscontainers.azurecr.io/dts-emp-dir-server:$BUILD_NUMBER
      
